defmodule Tptp.Bnf.Vocabulary do
  @moduledoc """
  The closed vocabularies of the TPTP `:==` semantic layer.

  DO NOT EDIT. Generated by `mix tptp.gen` from
  `priv/bnf/SyntaxBNF-v9.3.1.2`.

  The grammar accepts far more than these lists do: `<formula_role> ::=
  <lower_word>` admits any lower word, and `<defined_functor> ::=
  <atomic_defined_word>` admits any `$`-word. Membership here is what
  separates a well-formed statement from a merely parseable one, and it is
  checked by `Tptp.Lint` at warning severity rather than by the parser.
  """

  @defined_functor_values [
    "$uminus",
    "$sum",
    "$difference",
    "$product",
    "$quotient",
    "$quotient_e",
    "$quotient_t",
    "$quotient_f",
    "$remainder_e",
    "$remainder_t",
    "$remainder_f",
    "$floor",
    "$ceiling",
    "$truncate",
    "$round",
    "$to_int",
    "$to_rat",
    "$to_real"
  ]

  @doc """
  The 18 values the BNF lists for `<defined_functor>`.
  """
  @spec defined_functor_values() :: [binary()]
  def defined_functor_values, do: @defined_functor_values

  @doc """
  Whether `word` is one of the 18 `<defined_functor>` values.
  """
  @spec defined_functor?(binary()) :: boolean()
  def defined_functor?("$uminus"), do: true
  def defined_functor?("$sum"), do: true
  def defined_functor?("$difference"), do: true
  def defined_functor?("$product"), do: true
  def defined_functor?("$quotient"), do: true
  def defined_functor?("$quotient_e"), do: true
  def defined_functor?("$quotient_t"), do: true
  def defined_functor?("$quotient_f"), do: true
  def defined_functor?("$remainder_e"), do: true
  def defined_functor?("$remainder_t"), do: true
  def defined_functor?("$remainder_f"), do: true
  def defined_functor?("$floor"), do: true
  def defined_functor?("$ceiling"), do: true
  def defined_functor?("$truncate"), do: true
  def defined_functor?("$round"), do: true
  def defined_functor?("$to_int"), do: true
  def defined_functor?("$to_rat"), do: true
  def defined_functor?("$to_real"), do: true
  def defined_functor?(word) when is_binary(word), do: false

  @defined_predicate_values [
    "$distinct",
    "$less",
    "$lesseq",
    "$greater",
    "$greatereq",
    "$is_int",
    "$is_rat"
  ]

  @doc """
  The 7 values the BNF lists for `<defined_predicate>`.
  """
  @spec defined_predicate_values() :: [binary()]
  def defined_predicate_values, do: @defined_predicate_values

  @doc """
  Whether `word` is one of the 7 `<defined_predicate>` values.
  """
  @spec defined_predicate?(binary()) :: boolean()
  def defined_predicate?("$distinct"), do: true
  def defined_predicate?("$less"), do: true
  def defined_predicate?("$lesseq"), do: true
  def defined_predicate?("$greater"), do: true
  def defined_predicate?("$greatereq"), do: true
  def defined_predicate?("$is_int"), do: true
  def defined_predicate?("$is_rat"), do: true
  def defined_predicate?(word) when is_binary(word), do: false

  @defined_proposition_values ["$true", "$false"]

  @doc """
  The 2 values the BNF lists for `<defined_proposition>`.
  """
  @spec defined_proposition_values() :: [binary()]
  def defined_proposition_values, do: @defined_proposition_values

  @doc """
  Whether `word` is one of the 2 `<defined_proposition>` values.
  """
  @spec defined_proposition?(binary()) :: boolean()
  def defined_proposition?("$true"), do: true
  def defined_proposition?("$false"), do: true
  def defined_proposition?(word) when is_binary(word), do: false

  @defined_type_values ["$oType", "$o", "$iType", "$i", "$tType", "$real", "$rat", "$int"]

  @doc """
  The 8 values the BNF lists for `<defined_type>`.
  """
  @spec defined_type_values() :: [binary()]
  def defined_type_values, do: @defined_type_values

  @doc """
  Whether `word` is one of the 8 `<defined_type>` values.
  """
  @spec defined_type?(binary()) :: boolean()
  def defined_type?("$oType"), do: true
  def defined_type?("$o"), do: true
  def defined_type?("$iType"), do: true
  def defined_type?("$i"), do: true
  def defined_type?("$tType"), do: true
  def defined_type?("$real"), do: true
  def defined_type?("$rat"), do: true
  def defined_type?("$int"), do: true
  def defined_type?(word) when is_binary(word), do: false

  @formula_role_values [
    "axiom",
    "hypothesis",
    "definition",
    "assumption",
    "lemma",
    "theorem",
    "corollary",
    "conjecture",
    "negated_conjecture",
    "plain",
    "type",
    "interpretation",
    "unknown"
  ]

  @doc """
  The 13 values the BNF lists for `<formula_role>`.
  """
  @spec formula_role_values() :: [binary()]
  def formula_role_values, do: @formula_role_values

  @doc """
  Whether `word` is one of the 13 `<formula_role>` values.
  """
  @spec formula_role?(binary()) :: boolean()
  def formula_role?("axiom"), do: true
  def formula_role?("hypothesis"), do: true
  def formula_role?("definition"), do: true
  def formula_role?("assumption"), do: true
  def formula_role?("lemma"), do: true
  def formula_role?("theorem"), do: true
  def formula_role?("corollary"), do: true
  def formula_role?("conjecture"), do: true
  def formula_role?("negated_conjecture"), do: true
  def formula_role?("plain"), do: true
  def formula_role?("type"), do: true
  def formula_role?("interpretation"), do: true
  def formula_role?("unknown"), do: true
  def formula_role?(word) when is_binary(word), do: false

  @intro_type_values ["definition", "tautology", "assumption", "theory"]

  @doc """
  The 4 values the BNF lists for `<intro_type>`.
  """
  @spec intro_type_values() :: [binary()]
  def intro_type_values, do: @intro_type_values

  @doc """
  Whether `word` is one of the 4 `<intro_type>` values.
  """
  @spec intro_type?(binary()) :: boolean()
  def intro_type?("definition"), do: true
  def intro_type?("tautology"), do: true
  def intro_type?("assumption"), do: true
  def intro_type?("theory"), do: true
  def intro_type?(word) when is_binary(word), do: false

  @ntf_connective_name_values [
    "$box",
    "$dia",
    "$necessary",
    "$possible",
    "$obligatory",
    "$permissible",
    "$knows",
    "$canKnow",
    "$believes",
    "$canBelieve"
  ]

  @doc """
  The 10 values the BNF lists for `<ntf_connective_name>`.
  """
  @spec ntf_connective_name_values() :: [binary()]
  def ntf_connective_name_values, do: @ntf_connective_name_values

  @doc """
  Whether `word` is one of the 10 `<ntf_connective_name>` values.
  """
  @spec ntf_connective_name?(binary()) :: boolean()
  def ntf_connective_name?("$box"), do: true
  def ntf_connective_name?("$dia"), do: true
  def ntf_connective_name?("$necessary"), do: true
  def ntf_connective_name?("$possible"), do: true
  def ntf_connective_name?("$obligatory"), do: true
  def ntf_connective_name?("$permissible"), do: true
  def ntf_connective_name?("$knows"), do: true
  def ntf_connective_name?("$canKnow"), do: true
  def ntf_connective_name?("$believes"), do: true
  def ntf_connective_name?("$canBelieve"), do: true
  def ntf_connective_name?(word) when is_binary(word), do: false

  @ntf_logic_name_values [
    "$modal",
    "$alethic_modal",
    "$deontic_modal",
    "$epistemic_modal",
    "$doxastic_modal",
    "$temporal_instant"
  ]

  @doc """
  The 6 values the BNF lists for `<ntf_logic_name>`.
  """
  @spec ntf_logic_name_values() :: [binary()]
  def ntf_logic_name_values, do: @ntf_logic_name_values

  @doc """
  Whether `word` is one of the 6 `<ntf_logic_name>` values.
  """
  @spec ntf_logic_name?(binary()) :: boolean()
  def ntf_logic_name?("$modal"), do: true
  def ntf_logic_name?("$alethic_modal"), do: true
  def ntf_logic_name?("$deontic_modal"), do: true
  def ntf_logic_name?("$epistemic_modal"), do: true
  def ntf_logic_name?("$doxastic_modal"), do: true
  def ntf_logic_name?("$temporal_instant"), do: true
  def ntf_logic_name?(word) when is_binary(word), do: false

  @ntf_modal_axiom_values [
    "$modal_axiom_K",
    "$modal_axiom_M",
    "$modal_axiom_B",
    "$modal_axiom_D",
    "$modal_axiom_4",
    "$modal_axiom_5"
  ]

  @doc """
  The 6 values the BNF lists for `<ntf_modal_axiom>`.
  """
  @spec ntf_modal_axiom_values() :: [binary()]
  def ntf_modal_axiom_values, do: @ntf_modal_axiom_values

  @doc """
  Whether `word` is one of the 6 `<ntf_modal_axiom>` values.
  """
  @spec ntf_modal_axiom?(binary()) :: boolean()
  def ntf_modal_axiom?("$modal_axiom_K"), do: true
  def ntf_modal_axiom?("$modal_axiom_M"), do: true
  def ntf_modal_axiom?("$modal_axiom_B"), do: true
  def ntf_modal_axiom?("$modal_axiom_D"), do: true
  def ntf_modal_axiom?("$modal_axiom_4"), do: true
  def ntf_modal_axiom?("$modal_axiom_5"), do: true
  def ntf_modal_axiom?(word) when is_binary(word), do: false

  @ntf_modal_system_values [
    "$modal_system_K",
    "$modal_system_M",
    "$modal_system_B",
    "$modal_system_D",
    "$modal_system_S4",
    "$modal_system_S5"
  ]

  @doc """
  The 6 values the BNF lists for `<ntf_modal_system>`.
  """
  @spec ntf_modal_system_values() :: [binary()]
  def ntf_modal_system_values, do: @ntf_modal_system_values

  @doc """
  Whether `word` is one of the 6 `<ntf_modal_system>` values.
  """
  @spec ntf_modal_system?(binary()) :: boolean()
  def ntf_modal_system?("$modal_system_K"), do: true
  def ntf_modal_system?("$modal_system_M"), do: true
  def ntf_modal_system?("$modal_system_B"), do: true
  def ntf_modal_system?("$modal_system_D"), do: true
  def ntf_modal_system?("$modal_system_S4"), do: true
  def ntf_modal_system?("$modal_system_S5"), do: true
  def ntf_modal_system?(word) when is_binary(word), do: false

  @status_value_values [
    "suc",
    "unp",
    "sap",
    "esa",
    "sat",
    "fsa",
    "thm",
    "eqv",
    "tac",
    "wec",
    "eth",
    "tau",
    "wtc",
    "wth",
    "cax",
    "sca",
    "tca",
    "wca",
    "cup",
    "csp",
    "ecs",
    "csa",
    "cth",
    "ceq",
    "unc",
    "wcc",
    "ect",
    "fun",
    "uns",
    "wuc",
    "wct",
    "scc",
    "uca",
    "noc"
  ]

  @doc """
  The 34 values the BNF lists for `<status_value>`.
  """
  @spec status_value_values() :: [binary()]
  def status_value_values, do: @status_value_values

  @doc """
  Whether `word` is one of the 34 `<status_value>` values.
  """
  @spec status_value?(binary()) :: boolean()
  def status_value?("suc"), do: true
  def status_value?("unp"), do: true
  def status_value?("sap"), do: true
  def status_value?("esa"), do: true
  def status_value?("sat"), do: true
  def status_value?("fsa"), do: true
  def status_value?("thm"), do: true
  def status_value?("eqv"), do: true
  def status_value?("tac"), do: true
  def status_value?("wec"), do: true
  def status_value?("eth"), do: true
  def status_value?("tau"), do: true
  def status_value?("wtc"), do: true
  def status_value?("wth"), do: true
  def status_value?("cax"), do: true
  def status_value?("sca"), do: true
  def status_value?("tca"), do: true
  def status_value?("wca"), do: true
  def status_value?("cup"), do: true
  def status_value?("csp"), do: true
  def status_value?("ecs"), do: true
  def status_value?("csa"), do: true
  def status_value?("cth"), do: true
  def status_value?("ceq"), do: true
  def status_value?("unc"), do: true
  def status_value?("wcc"), do: true
  def status_value?("ect"), do: true
  def status_value?("fun"), do: true
  def status_value?("uns"), do: true
  def status_value?("wuc"), do: true
  def status_value?("wct"), do: true
  def status_value?("scc"), do: true
  def status_value?("uca"), do: true
  def status_value?("noc"), do: true
  def status_value?(word) when is_binary(word), do: false

  @reserved_word_values [
    "$box",
    "$dia",
    "$necessary",
    "$possible",
    "$obligatory",
    "$permissible",
    "$knows",
    "$canKnow",
    "$believes",
    "$canBelieve",
    "$modal",
    "$alethic_modal",
    "$deontic_modal",
    "$epistemic_modal",
    "$doxastic_modal",
    "$temporal_instant",
    "$domains",
    "$constant",
    "$varying",
    "$cumulative",
    "$decreasing",
    "$designation",
    "$rigid",
    "$flexible",
    "$terms",
    "$local",
    "$global",
    "$modalities",
    "$time",
    "$reflexivity",
    "$irreflexivity",
    "$transitivity",
    "$asymmetry",
    "$anti_symmetry",
    "$linearity",
    "$forward_linearity",
    "$backward_linearity",
    "$beginning",
    "$end",
    "$no_beginning",
    "$no_end",
    "$density",
    "$forward_discreteness",
    "$backward_discreteness",
    "$modal_system_K",
    "$modal_system_M",
    "$modal_system_B",
    "$modal_system_D",
    "$modal_system_S4",
    "$modal_system_S5",
    "$modal_axiom_K",
    "$modal_axiom_M",
    "$modal_axiom_B",
    "$modal_axiom_D",
    "$modal_axiom_4",
    "$modal_axiom_5",
    "$oType",
    "$o",
    "$iType",
    "$i",
    "$tType",
    "$real",
    "$rat",
    "$int",
    "$true",
    "$false",
    "$distinct",
    "$less",
    "$lesseq",
    "$greater",
    "$greatereq",
    "$is_int",
    "$is_rat",
    "$uminus",
    "$sum",
    "$difference",
    "$product",
    "$quotient",
    "$quotient_e",
    "$quotient_t",
    "$quotient_f",
    "$remainder_e",
    "$remainder_t",
    "$remainder_f",
    "$floor",
    "$ceiling",
    "$truncate",
    "$round",
    "$to_int",
    "$to_rat",
    "$to_real"
  ]

  @doc """
  The 91 values the BNF lists for `<reserved_word>`.
  """
  @spec reserved_word_values() :: [binary()]
  def reserved_word_values, do: @reserved_word_values

  @doc """
  Whether `word` is one of the 91 `<reserved_word>` values.
  """
  @spec reserved_word?(binary()) :: boolean()
  def reserved_word?("$box"), do: true
  def reserved_word?("$dia"), do: true
  def reserved_word?("$necessary"), do: true
  def reserved_word?("$possible"), do: true
  def reserved_word?("$obligatory"), do: true
  def reserved_word?("$permissible"), do: true
  def reserved_word?("$knows"), do: true
  def reserved_word?("$canKnow"), do: true
  def reserved_word?("$believes"), do: true
  def reserved_word?("$canBelieve"), do: true
  def reserved_word?("$modal"), do: true
  def reserved_word?("$alethic_modal"), do: true
  def reserved_word?("$deontic_modal"), do: true
  def reserved_word?("$epistemic_modal"), do: true
  def reserved_word?("$doxastic_modal"), do: true
  def reserved_word?("$temporal_instant"), do: true
  def reserved_word?("$domains"), do: true
  def reserved_word?("$constant"), do: true
  def reserved_word?("$varying"), do: true
  def reserved_word?("$cumulative"), do: true
  def reserved_word?("$decreasing"), do: true
  def reserved_word?("$designation"), do: true
  def reserved_word?("$rigid"), do: true
  def reserved_word?("$flexible"), do: true
  def reserved_word?("$terms"), do: true
  def reserved_word?("$local"), do: true
  def reserved_word?("$global"), do: true
  def reserved_word?("$modalities"), do: true
  def reserved_word?("$time"), do: true
  def reserved_word?("$reflexivity"), do: true
  def reserved_word?("$irreflexivity"), do: true
  def reserved_word?("$transitivity"), do: true
  def reserved_word?("$asymmetry"), do: true
  def reserved_word?("$anti_symmetry"), do: true
  def reserved_word?("$linearity"), do: true
  def reserved_word?("$forward_linearity"), do: true
  def reserved_word?("$backward_linearity"), do: true
  def reserved_word?("$beginning"), do: true
  def reserved_word?("$end"), do: true
  def reserved_word?("$no_beginning"), do: true
  def reserved_word?("$no_end"), do: true
  def reserved_word?("$density"), do: true
  def reserved_word?("$forward_discreteness"), do: true
  def reserved_word?("$backward_discreteness"), do: true
  def reserved_word?("$modal_system_K"), do: true
  def reserved_word?("$modal_system_M"), do: true
  def reserved_word?("$modal_system_B"), do: true
  def reserved_word?("$modal_system_D"), do: true
  def reserved_word?("$modal_system_S4"), do: true
  def reserved_word?("$modal_system_S5"), do: true
  def reserved_word?("$modal_axiom_K"), do: true
  def reserved_word?("$modal_axiom_M"), do: true
  def reserved_word?("$modal_axiom_B"), do: true
  def reserved_word?("$modal_axiom_D"), do: true
  def reserved_word?("$modal_axiom_4"), do: true
  def reserved_word?("$modal_axiom_5"), do: true
  def reserved_word?("$oType"), do: true
  def reserved_word?("$o"), do: true
  def reserved_word?("$iType"), do: true
  def reserved_word?("$i"), do: true
  def reserved_word?("$tType"), do: true
  def reserved_word?("$real"), do: true
  def reserved_word?("$rat"), do: true
  def reserved_word?("$int"), do: true
  def reserved_word?("$true"), do: true
  def reserved_word?("$false"), do: true
  def reserved_word?("$distinct"), do: true
  def reserved_word?("$less"), do: true
  def reserved_word?("$lesseq"), do: true
  def reserved_word?("$greater"), do: true
  def reserved_word?("$greatereq"), do: true
  def reserved_word?("$is_int"), do: true
  def reserved_word?("$is_rat"), do: true
  def reserved_word?("$uminus"), do: true
  def reserved_word?("$sum"), do: true
  def reserved_word?("$difference"), do: true
  def reserved_word?("$product"), do: true
  def reserved_word?("$quotient"), do: true
  def reserved_word?("$quotient_e"), do: true
  def reserved_word?("$quotient_t"), do: true
  def reserved_word?("$quotient_f"), do: true
  def reserved_word?("$remainder_e"), do: true
  def reserved_word?("$remainder_t"), do: true
  def reserved_word?("$remainder_f"), do: true
  def reserved_word?("$floor"), do: true
  def reserved_word?("$ceiling"), do: true
  def reserved_word?("$truncate"), do: true
  def reserved_word?("$round"), do: true
  def reserved_word?("$to_int"), do: true
  def reserved_word?("$to_rat"), do: true
  def reserved_word?("$to_real"), do: true
  def reserved_word?(word) when is_binary(word), do: false
end
