defmodule Tptp.Printer.Shapes do
  @moduledoc """
  How each node kind is spelled, derived from the grammar.

  DO NOT EDIT. Generated by `mix tptp.gen` from
  `SyntaxBNF-v9.3.1.2`.

  A shape is a list of items in source order: `:slot` takes the next child, a
  binary is a literal to emit. `{:separated, ","}` is a variadic list — every
  child, joined by that literal.

  Keyed by kind and child count, which the grammar makes sufficient. Anything
  not listed is a leaf, and prints its own text.

  A separated list is the exception, and matches any arity: the grammar writes
  `<tff_arguments> ::= <tff_term><comma_tff_term>*`, so its production has two
  symbols however many arguments the call actually has.
  """

  @typedoc "One item of a shape: a child slot or a literal."
  @type item :: :slot | binary()

  @typedoc "How a node kind is spelled."
  @type t :: [item()] | {:separated, binary()}

  @doc """
  The shape for a node kind at a child count, or `nil` for a leaf.
  """
  @spec shape(atom(), non_neg_integer()) :: t() | nil
  def shape(:fof_formula_tuple_list, arity) when is_integer(arity), do: {:separated, ","}
  def shape(:general_terms, arity) when is_integer(arity), do: {:separated, ","}
  def shape(:parent_list, arity) when is_integer(arity), do: {:separated, ","}
  def shape(:tff_arguments, arity) when is_integer(arity), do: {:separated, ","}
  def shape(:thf_formula_list, arity) when is_integer(arity), do: {:separated, ","}
  def shape(:annotations, 2), do: [",", :slot, :slot]
  def shape(:cnf_annotated, 4), do: ["cnf", "(", :slot, ",", :slot, ",", :slot, :slot, ")", "."]
  def shape(:cnf_disjunction, 2), do: [:slot, "|", :slot]
  def shape(:cnf_formula, 1), do: ["(", :slot, ")"]
  def shape(:cnf_literal, 1), do: ["~", :slot]
  def shape(:constant, 1), do: [:slot]
  def shape(:defined_constant, 1), do: [:slot]
  def shape(:defined_functor, 1), do: [:slot]
  def shape(:defined_type, 1), do: [:slot]
  def shape(:file_info, 1), do: [",", :slot]
  def shape(:file_name, 1), do: [:slot]
  def shape(:file_source, 2), do: ["file", "(", :slot, :slot, ")"]
  def shape(:fof_and_formula, 2), do: [:slot, "&", :slot]
  def shape(:fof_annotated, 4), do: ["fof", "(", :slot, ",", :slot, ",", :slot, :slot, ")", "."]
  def shape(:fof_arguments, 2), do: [:slot, ",", :slot]
  def shape(:fof_binary_nonassoc, 3), do: [:slot, :slot, :slot]
  def shape(:fof_defined_infix_formula, 2), do: [:slot, "=", :slot]
  def shape(:fof_defined_plain_term, 2), do: [:slot, "(", :slot, ")"]
  def shape(:fof_formula_tuple, 0), do: ["[", "]"]
  def shape(:fof_formula_tuple, 1), do: ["[", :slot, "]"]
  def shape(:fof_infix_unary, 2), do: [:slot, "!=", :slot]
  def shape(:fof_or_formula, 2), do: [:slot, "|", :slot]
  def shape(:fof_plain_term, 2), do: [:slot, "(", :slot, ")"]
  def shape(:fof_quantified_formula, 3), do: [:slot, "[", :slot, "]", ":", :slot]
  def shape(:fof_sequent, 1), do: ["(", :slot, ")"]
  def shape(:fof_sequent, 2), do: [:slot, "-->", :slot]
  def shape(:fof_system_term, 2), do: [:slot, "(", :slot, ")"]
  def shape(:fof_unary_formula, 1), do: ["~", :slot]
  def shape(:fof_unitary_formula, 1), do: ["(", :slot, ")"]
  def shape(:fof_variable_list, 2), do: [:slot, ",", :slot]
  def shape(:formula_data, 2), do: [:slot, "(", :slot, ")"]
  def shape(:formula_role, 1), do: [:slot]
  def shape(:formula_role, 2), do: [:slot, "-", :slot]
  def shape(:formula_selection, 1), do: ["[", :slot, "]"]
  def shape(:functor, 1), do: [:slot]
  def shape(:general_function, 2), do: [:slot, "(", :slot, ")"]
  def shape(:general_list, 0), do: ["[", "]"]
  def shape(:general_list, 1), do: ["[", :slot, "]"]
  def shape(:general_term, 2), do: [:slot, ":", :slot]
  def shape(:include, 2), do: ["include", "(", :slot, :slot, ")", "."]
  def shape(:include_optionals, 1), do: [",", :slot]
  def shape(:include_optionals, 2), do: [",", :slot, ",", :slot]
  def shape(:inference_record, 3), do: ["inference", "(", :slot, ",", :slot, ",", :slot, ")"]
  def shape(:inference_rule, 1), do: [:slot]
  def shape(:internal_source, 3), do: ["introduced", "(", :slot, ",", :slot, ",", :slot, ")"]
  def shape(:intro_type, 1), do: [:slot]
  def shape(:name, 1), do: [:slot]
  def shape(:name_list, 2), do: [:slot, ",", :slot]
  def shape(:nhf_long_connective, 1), do: ["{", :slot, "}"]
  def shape(:nhf_long_connective, 2), do: ["{", :slot, "(", :slot, ")", "}"]
  def shape(:nhf_parameter_list, 2), do: [:slot, ",", :slot]
  def shape(:ntf_index, 1), do: ["#", :slot]
  def shape(:nxf_atom, 2), do: [:slot, "@", "(", :slot, ")"]
  def shape(:nxf_long_connective, 1), do: ["{", :slot, "}"]
  def shape(:nxf_long_connective, 2), do: ["{", :slot, "(", :slot, ")", "}"]
  def shape(:nxf_parameter_list, 2), do: [:slot, ",", :slot]
  def shape(:optional_info, 1), do: [",", :slot]
  def shape(:parent_details, 1), do: [":", :slot]
  def shape(:parent_info, 2), do: [:slot, :slot]
  def shape(:parents, 0), do: ["[", "]"]
  def shape(:parents, 1), do: ["[", :slot, "]"]
  def shape(:source, 1), do: ["[", :slot, "]"]
  def shape(:sources, 2), do: [:slot, ",", :slot]
  def shape(:system_constant, 1), do: [:slot]
  def shape(:system_functor, 1), do: [:slot]
  def shape(:system_type, 1), do: [:slot]
  def shape(:tcf_annotated, 4), do: ["tcf", "(", :slot, ",", :slot, ",", :slot, :slot, ")", "."]
  def shape(:tcf_quantified_formula, 2), do: ["!", "[", :slot, "]", ":", :slot]
  def shape(:tf1_quantified_type, 3), do: [:slot, "[", :slot, "]", ":", :slot]
  def shape(:tff_and_formula, 2), do: [:slot, "&", :slot]
  def shape(:tff_annotated, 4), do: ["tff", "(", :slot, ",", :slot, ",", :slot, :slot, ")", "."]
  def shape(:tff_atom_typing, 1), do: ["(", :slot, ")"]
  def shape(:tff_atom_typing, 2), do: [:slot, ":", :slot]
  def shape(:tff_atom_typing_list, 2), do: [:slot, ",", :slot]
  def shape(:tff_atomic_type, 1), do: ["(", :slot, ")"]
  def shape(:tff_atomic_type, 2), do: [:slot, "(", :slot, ")"]
  def shape(:tff_binary_nonassoc, 3), do: [:slot, :slot, :slot]
  def shape(:tff_defined_infix, 2), do: [:slot, "=", :slot]
  def shape(:tff_defined_plain, 2), do: [:slot, "(", :slot, ")"]
  def shape(:tff_infix_unary, 2), do: [:slot, "!=", :slot]
  def shape(:tff_mapping_type, 2), do: [:slot, ">", :slot]
  def shape(:tff_monotype, 1), do: ["(", :slot, ")"]
  def shape(:tff_non_atomic_type, 1), do: ["(", :slot, ")"]
  def shape(:tff_or_formula, 2), do: [:slot, "|", :slot]
  def shape(:tff_plain_atomic, 2), do: [:slot, "(", :slot, ")"]
  def shape(:tff_prefix_unary, 2), do: [:slot, :slot]
  def shape(:tff_quantified_formula, 3), do: [:slot, "[", :slot, "]", ":", :slot]
  def shape(:tff_subtype, 2), do: [:slot, "<<", :slot]
  def shape(:tff_system_atomic, 2), do: [:slot, "(", :slot, ")"]
  def shape(:tff_type_arguments, 2), do: [:slot, ",", :slot]
  def shape(:tff_type_list, 2), do: [:slot, ",", :slot]
  def shape(:tff_typed_variable, 2), do: [:slot, ":", :slot]
  def shape(:tff_unitary_formula, 1), do: ["(", :slot, ")"]
  def shape(:tff_unitary_term, 1), do: ["(", :slot, ")"]
  def shape(:tff_unitary_type, 1), do: ["(", :slot, ")"]
  def shape(:tff_variable_list, 2), do: [:slot, ",", :slot]
  def shape(:tff_xprod_type, 2), do: [:slot, "*", :slot]
  def shape(:thf_and_formula, 2), do: [:slot, "&", :slot]
  def shape(:thf_annotated, 4), do: ["thf", "(", :slot, ",", :slot, ",", :slot, :slot, ")", "."]
  def shape(:thf_apply_formula, 2), do: [:slot, "@", :slot]
  def shape(:thf_atom_typing, 1), do: ["(", :slot, ")"]
  def shape(:thf_atom_typing, 2), do: [:slot, ":", :slot]
  def shape(:thf_atom_typing_list, 2), do: [:slot, ",", :slot]
  def shape(:thf_binary_nonassoc, 3), do: [:slot, :slot, :slot]
  def shape(:thf_defined_atomic, 1), do: ["(", :slot, ")"]
  def shape(:thf_defined_infix, 2), do: [:slot, "=", :slot]
  def shape(:thf_definition, 2), do: [:slot, "==", :slot]
  def shape(:thf_fof_function, 2), do: [:slot, "(", :slot, ")"]
  def shape(:thf_infix_unary, 2), do: [:slot, "!=", :slot]
  def shape(:thf_let, 3), do: ["$let", "(", :slot, ",", :slot, ",", :slot, ")"]
  def shape(:thf_let_defn, 2), do: [:slot, ":=", :slot]
  def shape(:thf_let_defn_list, 2), do: [:slot, ",", :slot]
  def shape(:thf_let_defns, 1), do: ["[", :slot, "]"]
  def shape(:thf_let_types, 1), do: ["[", :slot, "]"]
  def shape(:thf_mapping_type, 2), do: [:slot, ">", :slot]
  def shape(:thf_or_formula, 2), do: [:slot, "|", :slot]
  def shape(:thf_prefix_unary, 2), do: [:slot, :slot]
  def shape(:thf_quantification, 2), do: [:slot, "[", :slot, "]", ":"]
  def shape(:thf_quantified_formula, 2), do: [:slot, :slot]
  def shape(:thf_sequent, 2), do: [:slot, "-->", :slot]
  def shape(:thf_subtype, 2), do: [:slot, "<<", :slot]
  def shape(:thf_tuple, 0), do: ["[", "]"]
  def shape(:thf_tuple, 1), do: ["[", :slot, "]"]
  def shape(:thf_typed_variable, 2), do: [:slot, ":", :slot]
  def shape(:thf_union_type, 2), do: [:slot, "+", :slot]
  def shape(:thf_unitary_formula, 1), do: ["(", :slot, ")"]
  def shape(:thf_unitary_term, 1), do: ["(", :slot, ")"]
  def shape(:thf_variable_list, 2), do: [:slot, ",", :slot]
  def shape(:thf_xprod_type, 2), do: [:slot, "*", :slot]
  def shape(:tpi_annotated, 4), do: ["tpi", "(", :slot, ",", :slot, ",", :slot, :slot, ")", "."]
  def shape(:txf_definition, 2), do: [:slot, "==", :slot]
  def shape(:txf_let, 3), do: ["$let", "(", :slot, ",", :slot, ",", :slot, ")"]
  def shape(:txf_let_defn, 2), do: [:slot, ":=", :slot]
  def shape(:txf_let_defn_list, 2), do: [:slot, ",", :slot]
  def shape(:txf_let_defns, 1), do: ["[", :slot, "]"]
  def shape(:txf_let_types, 1), do: ["[", :slot, "]"]
  def shape(:txf_sequent, 2), do: [:slot, "-->", :slot]
  def shape(:txf_tuple, 0), do: ["[", "]"]
  def shape(:txf_tuple, 1), do: ["[", :slot, "]"]
  def shape(:txf_tuple_type, 1), do: ["[", :slot, "]"]
  def shape(:type_constant, 1), do: [:slot]
  def shape(:type_functor, 1), do: [:slot]
  def shape(:variable, 1), do: [:slot]
  def shape(kind, arity) when is_atom(kind) and is_integer(arity), do: nil
end
