%% DO NOT EDIT. Generated by `mix tptp.gen` from
%% priv/bnf/SyntaxBNF-v9.3.1.2.
%%
%% Every action is one of three templates:
%%
%%   {'$node', Kind, Alt, Children, Open, Close}
%%   {'$leaf', Category, Alt, Token}   an alternative that is a single fixed token
%%   '$N'                              a transparent rule, spliced through
%%
%% Open and Close are the production's first and last symbols when those are
%% punctuation, and so are dropped from Children -- they are what lets a node's
%% span cover its own brackets. Either is nil when that position is already a
%% child, which anchors the span by itself.
%%
%% `Tptp.Parser` turns these into `%Tptp.Node{}`, attaches spans and collapses
%% the significant chain rules onto their leaves.

Nonterminals
  'TPTP_input' 'annotated_formula' 'tpi_annotated' 'tpi_formula' 'thf_annotated' 'tff_annotated'
  'tcf_annotated' 'fof_annotated' 'cnf_annotated' 'annotations' 'formula_role' 'thf_formula'
  'thf_logic_formula' 'thf_binary_formula' 'thf_binary_nonassoc' 'thf_binary_assoc' 'thf_or_formula' 'thf_and_formula'
  'thf_apply_formula' 'thf_unit_formula' 'thf_preunit_formula' 'thf_unitary_formula' 'thf_quantified_formula' 'thf_quantification'
  'thf_variable_list' 'thf_typed_variable' 'thf_unary_formula' 'thf_prefix_unary' 'thf_infix_unary' 'thf_atomic_formula'
  'thf_plain_atomic' 'thf_defined_atomic' 'thf_defined_term' 'thf_defined_infix' 'thf_system_atomic' 'thf_let'
  'thf_let_types' 'thf_atom_typing_list' 'thf_let_defns' 'thf_let_defn' 'thf_let_defn_list' 'thf_unitary_term'
  'thf_conn_term' 'thf_tuple' 'thf_fof_function' 'thf_arguments' 'thf_formula_list' 'comma_thf_logic_formula'
  'thf_atom_typing' 'thf_top_level_type' 'thf_unitary_type' 'thf_apply_type' 'thf_binary_type' 'thf_mapping_type'
  'thf_xprod_type' 'thf_union_type' 'thf_subtype' 'thf_definition' 'thf_sequent' 'tff_formula'
  'tff_logic_formula' 'tff_binary_formula' 'tff_binary_nonassoc' 'tff_binary_assoc' 'tff_or_formula' 'tff_and_formula'
  'tff_unit_formula' 'tff_preunit_formula' 'tff_unitary_formula' 'txf_unitary_formula' 'tff_quantified_formula' 'tff_variable_list'
  'tff_variable' 'tff_typed_variable' 'tff_unary_formula' 'tff_prefix_unary' 'tff_infix_unary' 'tff_atomic_formula'
  'tff_plain_atomic' 'tff_defined_atomic' 'tff_defined_plain' 'tff_defined_infix' 'tff_system_atomic' 'txf_let'
  'txf_let_types' 'tff_atom_typing_list' 'txf_let_defns' 'txf_let_defn' 'txf_let_LHS' 'txf_let_defn_list'
  'nxf_atom' 'tff_term' 'tff_unitary_term' 'txf_tuple' 'tff_arguments' 'comma_tff_term'
  'tff_atom_typing' 'tff_top_level_type' 'tff_non_atomic_type' 'tf1_quantified_type' 'tff_monotype' 'tff_unitary_type'
  'tff_atomic_type' 'tff_type_arguments' 'tff_mapping_type' 'tff_xprod_type' 'txf_tuple_type' 'tff_type_list'
  'tff_subtype' 'txf_definition' 'txf_sequent' 'nhf_long_connective' 'nhf_parameter_list' 'nhf_parameter'
  'nhf_key_pair' 'nxf_long_connective' 'nxf_parameter_list' 'nxf_parameter' 'nxf_key_pair' 'ntf_connective_name'
  'ntf_index' 'ntf_short_connective' 'tcf_formula' 'tcf_logic_formula' 'tcf_quantified_formula' 'fof_formula'
  'fof_logic_formula' 'fof_binary_formula' 'fof_binary_nonassoc' 'fof_binary_assoc' 'fof_or_formula' 'fof_and_formula'
  'fof_unary_formula' 'fof_infix_unary' 'fof_unit_formula' 'fof_unitary_formula' 'fof_quantified_formula' 'fof_variable_list'
  'fof_atomic_formula' 'fof_plain_atomic_formula' 'fof_defined_atomic_formula' 'fof_defined_plain_formula' 'fof_defined_infix_formula' 'fof_system_atomic_formula'
  'fof_plain_term' 'fof_defined_term' 'fof_defined_atomic_term' 'fof_defined_plain_term' 'fof_system_term' 'fof_arguments'
  'fof_term' 'fof_function_term' 'fof_sequent' 'fof_formula_tuple' 'fof_formula_tuple_list' 'comma_fof_logic_formula'
  'cnf_formula' 'cnf_disjunction' 'cnf_literal' 'thf_quantifier' 'thf_unary_connective' 'th0_quantifier'
  'type_quantifier' 'tff_unary_connective' 'tff_quantifier' 'fof_quantifier' 'nonassoc_connective' 'assoc_connective'
  'typeable_atom' 'atomic_type' 'type_constant' 'type_functor' 'defined_type' 'system_type'
  'constant' 'functor' 'defined_constant' 'defined_functor' 'system_constant' 'system_functor'
  'th1_defined_term' 'defined_term' 'variable' 'source' 'sources' 'dag_source'
  'inference_record' 'inference_rule' 'internal_source' 'intro_type' 'external_source' 'file_source'
  'file_info' 'parents' 'parent_list' 'comma_parent_info' 'parent_info' 'parent_details'
  'optional_info' 'useful_info' 'include' 'include_optionals' 'formula_selection' 'name_list'
  'space_name' 'general_term' 'general_data' 'general_function' 'formula_data' 'general_list'
  'general_terms' 'comma_general_term' 'name' 'atomic_word' 'number' 'file_name'
  'comma_thf_logic_formula_rep' 'comma_tff_term_rep' 'comma_fof_logic_formula_rep' 'comma_parent_info_rep' 'comma_general_term_rep'.

Terminals
  'kw_tpi' 'lparen' 'comma' 'rparen' 'dot' 'kw_thf'
  'kw_tff' 'kw_tcf' 'kw_fof' 'kw_cnf' 'lower_word' 'minus'
  'vline' 'ampersand' 'apply' 'lbracket' 'rbracket' 'colon'
  'not_equal' 'equal' 'dw_let' 'assign' 'arrow' 'star'
  'plus' 'subtype_sign' 'identical' 'gentzen_arrow' 'lbrace' 'rbrace'
  'dollar_word' 'dollar_dollar_word' 'hash' 'short_bracket' 'short_angle' 'short_brace'
  'short_paren' 'forall' 'tilde' 'lambda' 'choice' 'desc'
  'type_forall' 'type_exists' 'exists' 'iff' 'implies' 'impliedby'
  'xor' 'nor' 'nand' 'distinct_object' 'big_forall' 'big_exists'
  'big_choice' 'big_desc' 'big_equal' 'upper_word' 'kw_inference' 'kw_introduced'
  'kw_file' 'kw_include' 'dw_thf' 'dw_tff' 'dw_fof' 'dw_cnf'
  'dw_fot' 'integer' 'single_quoted' 'back_quoted' 'rational' 'real'.

Rootsymbol 'TPTP_input'.

'TPTP_input' -> 'annotated_formula' : '$1'.
'TPTP_input' -> 'include' : '$1'.
'annotated_formula' -> 'thf_annotated' : '$1'.
'annotated_formula' -> 'tff_annotated' : '$1'.
'annotated_formula' -> 'tcf_annotated' : '$1'.
'annotated_formula' -> 'fof_annotated' : '$1'.
'annotated_formula' -> 'cnf_annotated' : '$1'.
'annotated_formula' -> 'tpi_annotated' : '$1'.
'tpi_annotated' -> 'kw_tpi' 'lparen' 'name' 'comma' 'formula_role' 'comma' 'tpi_formula' 'annotations' 'rparen' 'dot' : {'$node', 'tpi_annotated', 0, ['$3', '$5', '$7', '$8'], '$1', '$10'}.
'tpi_formula' -> 'fof_formula' : '$1'.
'thf_annotated' -> 'kw_thf' 'lparen' 'name' 'comma' 'formula_role' 'comma' 'thf_formula' 'annotations' 'rparen' 'dot' : {'$node', 'thf_annotated', 0, ['$3', '$5', '$7', '$8'], '$1', '$10'}.
'tff_annotated' -> 'kw_tff' 'lparen' 'name' 'comma' 'formula_role' 'comma' 'tff_formula' 'annotations' 'rparen' 'dot' : {'$node', 'tff_annotated', 0, ['$3', '$5', '$7', '$8'], '$1', '$10'}.
'tcf_annotated' -> 'kw_tcf' 'lparen' 'name' 'comma' 'formula_role' 'comma' 'tcf_formula' 'annotations' 'rparen' 'dot' : {'$node', 'tcf_annotated', 0, ['$3', '$5', '$7', '$8'], '$1', '$10'}.
'fof_annotated' -> 'kw_fof' 'lparen' 'name' 'comma' 'formula_role' 'comma' 'fof_formula' 'annotations' 'rparen' 'dot' : {'$node', 'fof_annotated', 0, ['$3', '$5', '$7', '$8'], '$1', '$10'}.
'cnf_annotated' -> 'kw_cnf' 'lparen' 'name' 'comma' 'formula_role' 'comma' 'cnf_formula' 'annotations' 'rparen' 'dot' : {'$node', 'cnf_annotated', 0, ['$3', '$5', '$7', '$8'], '$1', '$10'}.
'annotations' -> 'comma' 'source' 'optional_info' : {'$node', 'annotations', 0, ['$2', '$3'], '$1', nil}.
'annotations' -> '$empty' : nil.
'formula_role' -> 'lower_word' : {'$node', 'formula_role', 0, ['$1'], nil, nil}.
'formula_role' -> 'lower_word' 'minus' 'general_term' : {'$node', 'formula_role', 1, ['$1', '$3'], nil, nil}.
'thf_formula' -> 'thf_logic_formula' : '$1'.
'thf_formula' -> 'thf_atom_typing' : '$1'.
'thf_formula' -> 'thf_subtype' : '$1'.
'thf_logic_formula' -> 'thf_unitary_formula' : '$1'.
'thf_logic_formula' -> 'thf_unary_formula' : '$1'.
'thf_logic_formula' -> 'thf_binary_formula' : '$1'.
'thf_logic_formula' -> 'thf_defined_infix' : '$1'.
'thf_logic_formula' -> 'thf_definition' : '$1'.
'thf_logic_formula' -> 'thf_sequent' : '$1'.
'thf_binary_formula' -> 'thf_binary_nonassoc' : '$1'.
'thf_binary_formula' -> 'thf_binary_assoc' : '$1'.
'thf_binary_formula' -> 'thf_binary_type' : '$1'.
'thf_binary_nonassoc' -> 'thf_unit_formula' 'nonassoc_connective' 'thf_unit_formula' : {'$node', 'thf_binary_nonassoc', 0, ['$1', '$2', '$3'], nil, nil}.
'thf_binary_assoc' -> 'thf_or_formula' : '$1'.
'thf_binary_assoc' -> 'thf_and_formula' : '$1'.
'thf_binary_assoc' -> 'thf_apply_formula' : '$1'.
'thf_or_formula' -> 'thf_unit_formula' 'vline' 'thf_unit_formula' : {'$node', 'thf_or_formula', 0, ['$1', '$3'], nil, nil}.
'thf_or_formula' -> 'thf_or_formula' 'vline' 'thf_unit_formula' : {'$node', 'thf_or_formula', 1, ['$1', '$3'], nil, nil}.
'thf_and_formula' -> 'thf_unit_formula' 'ampersand' 'thf_unit_formula' : {'$node', 'thf_and_formula', 0, ['$1', '$3'], nil, nil}.
'thf_and_formula' -> 'thf_and_formula' 'ampersand' 'thf_unit_formula' : {'$node', 'thf_and_formula', 1, ['$1', '$3'], nil, nil}.
'thf_apply_formula' -> 'thf_unit_formula' 'apply' 'thf_unit_formula' : {'$node', 'thf_apply_formula', 0, ['$1', '$3'], nil, nil}.
'thf_apply_formula' -> 'thf_apply_formula' 'apply' 'thf_unit_formula' : {'$node', 'thf_apply_formula', 1, ['$1', '$3'], nil, nil}.
'thf_unit_formula' -> 'thf_unitary_formula' : '$1'.
'thf_unit_formula' -> 'thf_unary_formula' : '$1'.
'thf_unit_formula' -> 'thf_defined_infix' : '$1'.
'thf_preunit_formula' -> 'thf_unitary_formula' : '$1'.
'thf_preunit_formula' -> 'thf_prefix_unary' : '$1'.
'thf_unitary_formula' -> 'thf_quantified_formula' : '$1'.
'thf_unitary_formula' -> 'thf_atomic_formula' : '$1'.
'thf_unitary_formula' -> 'variable' : '$1'.
'thf_unitary_formula' -> 'lparen' 'thf_logic_formula' 'rparen' : {'$node', 'thf_unitary_formula', 3, ['$2'], '$1', '$3'}.
'thf_quantified_formula' -> 'thf_quantification' 'thf_unit_formula' : {'$node', 'thf_quantified_formula', 0, ['$1', '$2'], nil, nil}.
'thf_quantification' -> 'thf_quantifier' 'lbracket' 'thf_variable_list' 'rbracket' 'colon' : {'$node', 'thf_quantification', 0, ['$1', '$3'], nil, '$5'}.
'thf_variable_list' -> 'thf_typed_variable' : '$1'.
'thf_variable_list' -> 'thf_typed_variable' 'comma' 'thf_variable_list' : {'$node', 'thf_variable_list', 1, ['$1', '$3'], nil, nil}.
'thf_typed_variable' -> 'variable' 'colon' 'thf_top_level_type' : {'$node', 'thf_typed_variable', 0, ['$1', '$3'], nil, nil}.
'thf_unary_formula' -> 'thf_prefix_unary' : '$1'.
'thf_unary_formula' -> 'thf_infix_unary' : '$1'.
'thf_prefix_unary' -> 'thf_unary_connective' 'thf_preunit_formula' : {'$node', 'thf_prefix_unary', 0, ['$1', '$2'], nil, nil}.
'thf_infix_unary' -> 'thf_unitary_term' 'not_equal' 'thf_unitary_term' : {'$node', 'thf_infix_unary', 0, ['$1', '$3'], nil, nil}.
'thf_atomic_formula' -> 'thf_plain_atomic' : '$1'.
'thf_atomic_formula' -> 'thf_defined_atomic' : '$1'.
'thf_atomic_formula' -> 'thf_system_atomic' : '$1'.
'thf_atomic_formula' -> 'thf_fof_function' : '$1'.
'thf_plain_atomic' -> 'constant' : '$1'.
'thf_plain_atomic' -> 'thf_tuple' : '$1'.
'thf_defined_atomic' -> 'defined_constant' : '$1'.
'thf_defined_atomic' -> 'thf_defined_term' : '$1'.
'thf_defined_atomic' -> 'lparen' 'thf_conn_term' 'rparen' : {'$node', 'thf_defined_atomic', 2, ['$2'], '$1', '$3'}.
'thf_defined_atomic' -> 'nhf_long_connective' : '$1'.
'thf_defined_atomic' -> 'thf_let' : '$1'.
'thf_defined_term' -> 'defined_term' : '$1'.
'thf_defined_term' -> 'th1_defined_term' : '$1'.
'thf_defined_infix' -> 'thf_unitary_term' 'equal' 'thf_unitary_term' : {'$node', 'thf_defined_infix', 0, ['$1', '$3'], nil, nil}.
'thf_system_atomic' -> 'system_constant' : '$1'.
'thf_let' -> 'dw_let' 'lparen' 'thf_let_types' 'comma' 'thf_let_defns' 'comma' 'thf_logic_formula' 'rparen' : {'$node', 'thf_let', 0, ['$3', '$5', '$7'], '$1', '$8'}.
'thf_let_types' -> 'thf_atom_typing' : '$1'.
'thf_let_types' -> 'lbracket' 'thf_atom_typing_list' 'rbracket' : {'$node', 'thf_let_types', 1, ['$2'], '$1', '$3'}.
'thf_atom_typing_list' -> 'thf_atom_typing' : '$1'.
'thf_atom_typing_list' -> 'thf_atom_typing' 'comma' 'thf_atom_typing_list' : {'$node', 'thf_atom_typing_list', 1, ['$1', '$3'], nil, nil}.
'thf_let_defns' -> 'thf_let_defn' : '$1'.
'thf_let_defns' -> 'lbracket' 'thf_let_defn_list' 'rbracket' : {'$node', 'thf_let_defns', 1, ['$2'], '$1', '$3'}.
'thf_let_defn' -> 'thf_logic_formula' 'assign' 'thf_logic_formula' : {'$node', 'thf_let_defn', 0, ['$1', '$3'], nil, nil}.
'thf_let_defn_list' -> 'thf_let_defn' : '$1'.
'thf_let_defn_list' -> 'thf_let_defn' 'comma' 'thf_let_defn_list' : {'$node', 'thf_let_defn_list', 1, ['$1', '$3'], nil, nil}.
'thf_unitary_term' -> 'thf_atomic_formula' : '$1'.
'thf_unitary_term' -> 'variable' : '$1'.
'thf_unitary_term' -> 'lparen' 'thf_logic_formula' 'rparen' : {'$node', 'thf_unitary_term', 2, ['$2'], '$1', '$3'}.
'thf_conn_term' -> 'nonassoc_connective' : '$1'.
'thf_conn_term' -> 'assoc_connective' : '$1'.
'thf_conn_term' -> 'equal' : {'$leaf', 'equal', 2, '$1'}.
'thf_conn_term' -> 'not_equal' : {'$leaf', 'not_equal', 3, '$1'}.
'thf_conn_term' -> 'thf_unary_connective' : '$1'.
'thf_tuple' -> 'lbracket' 'rbracket' : {'$node', 'thf_tuple', 0, [], '$1', '$2'}.
'thf_tuple' -> 'lbracket' 'thf_formula_list' 'rbracket' : {'$node', 'thf_tuple', 1, ['$2'], '$1', '$3'}.
'thf_fof_function' -> 'defined_functor' 'lparen' 'thf_arguments' 'rparen' : {'$node', 'thf_fof_function', 0, ['$1', '$3'], nil, '$4'}.
'thf_fof_function' -> 'system_functor' 'lparen' 'thf_arguments' 'rparen' : {'$node', 'thf_fof_function', 1, ['$1', '$3'], nil, '$4'}.
'thf_fof_function' -> 'functor' 'lparen' 'thf_arguments' 'rparen' : {'$node', 'thf_fof_function', 2, ['$1', '$3'], nil, '$4'}.
'thf_arguments' -> 'thf_formula_list' : '$1'.
'thf_formula_list' -> 'thf_logic_formula' 'comma_thf_logic_formula_rep' : {'$node', 'thf_formula_list', 0, ['$1'] ++ '$2', nil, nil}.
'comma_thf_logic_formula' -> 'comma' 'thf_logic_formula' : '$2'.
'thf_atom_typing' -> 'typeable_atom' 'colon' 'thf_top_level_type' : {'$node', 'thf_atom_typing', 0, ['$1', '$3'], nil, nil}.
'thf_atom_typing' -> 'lparen' 'thf_atom_typing' 'rparen' : {'$node', 'thf_atom_typing', 1, ['$2'], '$1', '$3'}.
'thf_top_level_type' -> 'thf_unitary_type' : '$1'.
'thf_top_level_type' -> 'thf_mapping_type' : '$1'.
'thf_top_level_type' -> 'thf_apply_type' : '$1'.
'thf_unitary_type' -> 'thf_unitary_formula' : '$1'.
'thf_apply_type' -> 'thf_apply_formula' : '$1'.
'thf_binary_type' -> 'thf_mapping_type' : '$1'.
'thf_binary_type' -> 'thf_xprod_type' : '$1'.
'thf_binary_type' -> 'thf_union_type' : '$1'.
'thf_mapping_type' -> 'thf_unitary_type' 'arrow' 'thf_unitary_type' : {'$node', 'thf_mapping_type', 0, ['$1', '$3'], nil, nil}.
'thf_mapping_type' -> 'thf_unitary_type' 'arrow' 'thf_mapping_type' : {'$node', 'thf_mapping_type', 1, ['$1', '$3'], nil, nil}.
'thf_xprod_type' -> 'thf_unitary_type' 'star' 'thf_unitary_type' : {'$node', 'thf_xprod_type', 0, ['$1', '$3'], nil, nil}.
'thf_xprod_type' -> 'thf_xprod_type' 'star' 'thf_unitary_type' : {'$node', 'thf_xprod_type', 1, ['$1', '$3'], nil, nil}.
'thf_union_type' -> 'thf_unitary_type' 'plus' 'thf_unitary_type' : {'$node', 'thf_union_type', 0, ['$1', '$3'], nil, nil}.
'thf_union_type' -> 'thf_union_type' 'plus' 'thf_unitary_type' : {'$node', 'thf_union_type', 1, ['$1', '$3'], nil, nil}.
'thf_subtype' -> 'atomic_type' 'subtype_sign' 'atomic_type' : {'$node', 'thf_subtype', 0, ['$1', '$3'], nil, nil}.
'thf_definition' -> 'thf_atomic_formula' 'identical' 'thf_logic_formula' : {'$node', 'thf_definition', 0, ['$1', '$3'], nil, nil}.
'thf_sequent' -> 'thf_tuple' 'gentzen_arrow' 'thf_tuple' : {'$node', 'thf_sequent', 0, ['$1', '$3'], nil, nil}.
'tff_formula' -> 'tff_logic_formula' : '$1'.
'tff_formula' -> 'tff_atom_typing' : '$1'.
'tff_formula' -> 'tff_subtype' : '$1'.
'tff_logic_formula' -> 'tff_unitary_formula' : '$1'.
'tff_logic_formula' -> 'tff_unary_formula' : '$1'.
'tff_logic_formula' -> 'tff_binary_formula' : '$1'.
'tff_logic_formula' -> 'tff_defined_infix' : '$1'.
'tff_logic_formula' -> 'txf_definition' : '$1'.
'tff_logic_formula' -> 'txf_sequent' : '$1'.
'tff_binary_formula' -> 'tff_binary_nonassoc' : '$1'.
'tff_binary_formula' -> 'tff_binary_assoc' : '$1'.
'tff_binary_nonassoc' -> 'tff_unit_formula' 'nonassoc_connective' 'tff_unit_formula' : {'$node', 'tff_binary_nonassoc', 0, ['$1', '$2', '$3'], nil, nil}.
'tff_binary_assoc' -> 'tff_or_formula' : '$1'.
'tff_binary_assoc' -> 'tff_and_formula' : '$1'.
'tff_or_formula' -> 'tff_unit_formula' 'vline' 'tff_unit_formula' : {'$node', 'tff_or_formula', 0, ['$1', '$3'], nil, nil}.
'tff_or_formula' -> 'tff_or_formula' 'vline' 'tff_unit_formula' : {'$node', 'tff_or_formula', 1, ['$1', '$3'], nil, nil}.
'tff_and_formula' -> 'tff_unit_formula' 'ampersand' 'tff_unit_formula' : {'$node', 'tff_and_formula', 0, ['$1', '$3'], nil, nil}.
'tff_and_formula' -> 'tff_and_formula' 'ampersand' 'tff_unit_formula' : {'$node', 'tff_and_formula', 1, ['$1', '$3'], nil, nil}.
'tff_unit_formula' -> 'tff_unitary_formula' : '$1'.
'tff_unit_formula' -> 'tff_unary_formula' : '$1'.
'tff_unit_formula' -> 'tff_defined_infix' : '$1'.
'tff_preunit_formula' -> 'tff_unitary_formula' : '$1'.
'tff_preunit_formula' -> 'tff_prefix_unary' : '$1'.
'tff_unitary_formula' -> 'tff_quantified_formula' : '$1'.
'tff_unitary_formula' -> 'tff_atomic_formula' : '$1'.
'tff_unitary_formula' -> 'txf_unitary_formula' : '$1'.
'tff_unitary_formula' -> 'lparen' 'tff_logic_formula' 'rparen' : {'$node', 'tff_unitary_formula', 3, ['$2'], '$1', '$3'}.
'txf_unitary_formula' -> 'variable' : '$1'.
'tff_quantified_formula' -> 'tff_quantifier' 'lbracket' 'tff_variable_list' 'rbracket' 'colon' 'tff_unit_formula' : {'$node', 'tff_quantified_formula', 0, ['$1', '$3', '$6'], nil, nil}.
'tff_variable_list' -> 'tff_variable' : '$1'.
'tff_variable_list' -> 'tff_variable' 'comma' 'tff_variable_list' : {'$node', 'tff_variable_list', 1, ['$1', '$3'], nil, nil}.
'tff_variable' -> 'tff_typed_variable' : '$1'.
'tff_variable' -> 'variable' : '$1'.
'tff_typed_variable' -> 'variable' 'colon' 'tff_atomic_type' : {'$node', 'tff_typed_variable', 0, ['$1', '$3'], nil, nil}.
'tff_unary_formula' -> 'tff_prefix_unary' : '$1'.
'tff_unary_formula' -> 'tff_infix_unary' : '$1'.
'tff_prefix_unary' -> 'tff_unary_connective' 'tff_preunit_formula' : {'$node', 'tff_prefix_unary', 0, ['$1', '$2'], nil, nil}.
'tff_infix_unary' -> 'tff_unitary_term' 'not_equal' 'tff_unitary_term' : {'$node', 'tff_infix_unary', 0, ['$1', '$3'], nil, nil}.
'tff_atomic_formula' -> 'tff_plain_atomic' : '$1'.
'tff_atomic_formula' -> 'tff_defined_atomic' : '$1'.
'tff_atomic_formula' -> 'tff_system_atomic' : '$1'.
'tff_plain_atomic' -> 'constant' : '$1'.
'tff_plain_atomic' -> 'functor' 'lparen' 'tff_arguments' 'rparen' : {'$node', 'tff_plain_atomic', 1, ['$1', '$3'], nil, '$4'}.
'tff_defined_atomic' -> 'tff_defined_plain' : '$1'.
'tff_defined_plain' -> 'defined_constant' : '$1'.
'tff_defined_plain' -> 'defined_functor' 'lparen' 'tff_arguments' 'rparen' : {'$node', 'tff_defined_plain', 1, ['$1', '$3'], nil, '$4'}.
'tff_defined_plain' -> 'nxf_atom' : '$1'.
'tff_defined_plain' -> 'txf_let' : '$1'.
'tff_defined_infix' -> 'tff_unitary_term' 'equal' 'tff_unitary_term' : {'$node', 'tff_defined_infix', 0, ['$1', '$3'], nil, nil}.
'tff_system_atomic' -> 'system_constant' : '$1'.
'tff_system_atomic' -> 'system_functor' 'lparen' 'tff_arguments' 'rparen' : {'$node', 'tff_system_atomic', 1, ['$1', '$3'], nil, '$4'}.
'txf_let' -> 'dw_let' 'lparen' 'txf_let_types' 'comma' 'txf_let_defns' 'comma' 'tff_term' 'rparen' : {'$node', 'txf_let', 0, ['$3', '$5', '$7'], '$1', '$8'}.
'txf_let_types' -> 'tff_atom_typing' : '$1'.
'txf_let_types' -> 'lbracket' 'tff_atom_typing_list' 'rbracket' : {'$node', 'txf_let_types', 1, ['$2'], '$1', '$3'}.
'tff_atom_typing_list' -> 'tff_atom_typing' : '$1'.
'tff_atom_typing_list' -> 'tff_atom_typing' 'comma' 'tff_atom_typing_list' : {'$node', 'tff_atom_typing_list', 1, ['$1', '$3'], nil, nil}.
'txf_let_defns' -> 'txf_let_defn' : '$1'.
'txf_let_defns' -> 'lbracket' 'txf_let_defn_list' 'rbracket' : {'$node', 'txf_let_defns', 1, ['$2'], '$1', '$3'}.
'txf_let_defn' -> 'txf_let_LHS' 'assign' 'tff_term' : {'$node', 'txf_let_defn', 0, ['$1', '$3'], nil, nil}.
'txf_let_LHS' -> 'tff_plain_atomic' : '$1'.
'txf_let_LHS' -> 'txf_tuple' : '$1'.
'txf_let_defn_list' -> 'txf_let_defn' : '$1'.
'txf_let_defn_list' -> 'txf_let_defn' 'comma' 'txf_let_defn_list' : {'$node', 'txf_let_defn_list', 1, ['$1', '$3'], nil, nil}.
'nxf_atom' -> 'nxf_long_connective' 'apply' 'lparen' 'tff_arguments' 'rparen' : {'$node', 'nxf_atom', 0, ['$1', '$4'], nil, '$5'}.
'tff_term' -> 'tff_logic_formula' : '$1'.
'tff_term' -> 'defined_term' : '$1'.
'tff_term' -> 'txf_tuple' : '$1'.
'tff_unitary_term' -> 'tff_atomic_formula' : '$1'.
'tff_unitary_term' -> 'defined_term' : '$1'.
'tff_unitary_term' -> 'txf_tuple' : '$1'.
'tff_unitary_term' -> 'variable' : '$1'.
'tff_unitary_term' -> 'lparen' 'tff_logic_formula' 'rparen' : {'$node', 'tff_unitary_term', 4, ['$2'], '$1', '$3'}.
'txf_tuple' -> 'lbracket' 'rbracket' : {'$node', 'txf_tuple', 0, [], '$1', '$2'}.
'txf_tuple' -> 'lbracket' 'tff_arguments' 'rbracket' : {'$node', 'txf_tuple', 1, ['$2'], '$1', '$3'}.
'tff_arguments' -> 'tff_term' 'comma_tff_term_rep' : {'$node', 'tff_arguments', 0, ['$1'] ++ '$2', nil, nil}.
'comma_tff_term' -> 'comma' 'tff_term' : '$2'.
'tff_atom_typing' -> 'typeable_atom' 'colon' 'tff_top_level_type' : {'$node', 'tff_atom_typing', 0, ['$1', '$3'], nil, nil}.
'tff_atom_typing' -> 'lparen' 'tff_atom_typing' 'rparen' : {'$node', 'tff_atom_typing', 1, ['$2'], '$1', '$3'}.
'tff_top_level_type' -> 'tff_atomic_type' : '$1'.
'tff_top_level_type' -> 'tff_non_atomic_type' : '$1'.
'tff_non_atomic_type' -> 'tff_mapping_type' : '$1'.
'tff_non_atomic_type' -> 'tf1_quantified_type' : '$1'.
'tff_non_atomic_type' -> 'lparen' 'tff_non_atomic_type' 'rparen' : {'$node', 'tff_non_atomic_type', 2, ['$2'], '$1', '$3'}.
'tf1_quantified_type' -> 'type_quantifier' 'lbracket' 'tff_variable_list' 'rbracket' 'colon' 'tff_monotype' : {'$node', 'tf1_quantified_type', 0, ['$1', '$3', '$6'], nil, nil}.
'tff_monotype' -> 'tff_atomic_type' : '$1'.
'tff_monotype' -> 'lparen' 'tff_mapping_type' 'rparen' : {'$node', 'tff_monotype', 1, ['$2'], '$1', '$3'}.
'tff_monotype' -> 'tf1_quantified_type' : '$1'.
'tff_unitary_type' -> 'tff_atomic_type' : '$1'.
'tff_unitary_type' -> 'lparen' 'tff_xprod_type' 'rparen' : {'$node', 'tff_unitary_type', 1, ['$2'], '$1', '$3'}.
'tff_atomic_type' -> 'type_constant' : '$1'.
'tff_atomic_type' -> 'defined_type' : '$1'.
'tff_atomic_type' -> 'variable' : '$1'.
'tff_atomic_type' -> 'type_functor' 'lparen' 'tff_type_arguments' 'rparen' : {'$node', 'tff_atomic_type', 3, ['$1', '$3'], nil, '$4'}.
'tff_atomic_type' -> 'lparen' 'tff_atomic_type' 'rparen' : {'$node', 'tff_atomic_type', 4, ['$2'], '$1', '$3'}.
'tff_atomic_type' -> 'txf_tuple_type' : '$1'.
'tff_type_arguments' -> 'tff_atomic_type' : '$1'.
'tff_type_arguments' -> 'tff_atomic_type' 'comma' 'tff_type_arguments' : {'$node', 'tff_type_arguments', 1, ['$1', '$3'], nil, nil}.
'tff_mapping_type' -> 'tff_unitary_type' 'arrow' 'tff_atomic_type' : {'$node', 'tff_mapping_type', 0, ['$1', '$3'], nil, nil}.
'tff_xprod_type' -> 'tff_unitary_type' 'star' 'tff_atomic_type' : {'$node', 'tff_xprod_type', 0, ['$1', '$3'], nil, nil}.
'tff_xprod_type' -> 'tff_xprod_type' 'star' 'tff_atomic_type' : {'$node', 'tff_xprod_type', 1, ['$1', '$3'], nil, nil}.
'txf_tuple_type' -> 'lbracket' 'tff_type_list' 'rbracket' : {'$node', 'txf_tuple_type', 0, ['$2'], '$1', '$3'}.
'tff_type_list' -> 'tff_top_level_type' : '$1'.
'tff_type_list' -> 'tff_top_level_type' 'comma' 'tff_type_list' : {'$node', 'tff_type_list', 1, ['$1', '$3'], nil, nil}.
'tff_subtype' -> 'atomic_type' 'subtype_sign' 'atomic_type' : {'$node', 'tff_subtype', 0, ['$1', '$3'], nil, nil}.
'txf_definition' -> 'tff_atomic_formula' 'identical' 'tff_term' : {'$node', 'txf_definition', 0, ['$1', '$3'], nil, nil}.
'txf_sequent' -> 'txf_tuple' 'gentzen_arrow' 'txf_tuple' : {'$node', 'txf_sequent', 0, ['$1', '$3'], nil, nil}.
'nhf_long_connective' -> 'lbrace' 'ntf_connective_name' 'rbrace' : {'$node', 'nhf_long_connective', 0, ['$2'], '$1', '$3'}.
'nhf_long_connective' -> 'lbrace' 'ntf_connective_name' 'lparen' 'nhf_parameter_list' 'rparen' 'rbrace' : {'$node', 'nhf_long_connective', 1, ['$2', '$4'], '$1', '$6'}.
'nhf_parameter_list' -> 'nhf_parameter' : '$1'.
'nhf_parameter_list' -> 'nhf_parameter' 'comma' 'nhf_parameter_list' : {'$node', 'nhf_parameter_list', 1, ['$1', '$3'], nil, nil}.
'nhf_parameter' -> 'ntf_index' : '$1'.
'nhf_parameter' -> 'nhf_key_pair' : '$1'.
'nhf_key_pair' -> 'thf_definition' : '$1'.
'nxf_long_connective' -> 'lbrace' 'ntf_connective_name' 'rbrace' : {'$node', 'nxf_long_connective', 0, ['$2'], '$1', '$3'}.
'nxf_long_connective' -> 'lbrace' 'ntf_connective_name' 'lparen' 'nxf_parameter_list' 'rparen' 'rbrace' : {'$node', 'nxf_long_connective', 1, ['$2', '$4'], '$1', '$6'}.
'nxf_parameter_list' -> 'nxf_parameter' : '$1'.
'nxf_parameter_list' -> 'nxf_parameter' 'comma' 'nxf_parameter_list' : {'$node', 'nxf_parameter_list', 1, ['$1', '$3'], nil, nil}.
'nxf_parameter' -> 'ntf_index' : '$1'.
'nxf_parameter' -> 'nxf_key_pair' : '$1'.
'nxf_key_pair' -> 'txf_definition' : '$1'.
'ntf_connective_name' -> 'dollar_word' : '$1'.
'ntf_connective_name' -> 'dollar_dollar_word' : '$1'.
'ntf_index' -> 'hash' 'tff_unitary_term' : {'$node', 'ntf_index', 0, ['$2'], '$1', nil}.
'ntf_short_connective' -> 'short_bracket' : {'$leaf', 'short_bracket', 0, '$1'}.
'ntf_short_connective' -> 'short_angle' : {'$leaf', 'short_angle', 1, '$1'}.
'ntf_short_connective' -> 'short_brace' : {'$leaf', 'short_brace', 2, '$1'}.
'ntf_short_connective' -> 'short_paren' : {'$leaf', 'short_paren', 3, '$1'}.
'tcf_formula' -> 'tcf_logic_formula' : '$1'.
'tcf_formula' -> 'tff_atom_typing' : '$1'.
'tcf_logic_formula' -> 'tcf_quantified_formula' : '$1'.
'tcf_logic_formula' -> 'cnf_formula' : '$1'.
'tcf_quantified_formula' -> 'forall' 'lbracket' 'tff_variable_list' 'rbracket' 'colon' 'tcf_logic_formula' : {'$node', 'tcf_quantified_formula', 0, ['$3', '$6'], '$1', nil}.
'fof_formula' -> 'fof_logic_formula' : '$1'.
'fof_formula' -> 'fof_sequent' : '$1'.
'fof_logic_formula' -> 'fof_binary_formula' : '$1'.
'fof_logic_formula' -> 'fof_unary_formula' : '$1'.
'fof_logic_formula' -> 'fof_unitary_formula' : '$1'.
'fof_binary_formula' -> 'fof_binary_nonassoc' : '$1'.
'fof_binary_formula' -> 'fof_binary_assoc' : '$1'.
'fof_binary_nonassoc' -> 'fof_unit_formula' 'nonassoc_connective' 'fof_unit_formula' : {'$node', 'fof_binary_nonassoc', 0, ['$1', '$2', '$3'], nil, nil}.
'fof_binary_assoc' -> 'fof_or_formula' : '$1'.
'fof_binary_assoc' -> 'fof_and_formula' : '$1'.
'fof_or_formula' -> 'fof_unit_formula' 'vline' 'fof_unit_formula' : {'$node', 'fof_or_formula', 0, ['$1', '$3'], nil, nil}.
'fof_or_formula' -> 'fof_or_formula' 'vline' 'fof_unit_formula' : {'$node', 'fof_or_formula', 1, ['$1', '$3'], nil, nil}.
'fof_and_formula' -> 'fof_unit_formula' 'ampersand' 'fof_unit_formula' : {'$node', 'fof_and_formula', 0, ['$1', '$3'], nil, nil}.
'fof_and_formula' -> 'fof_and_formula' 'ampersand' 'fof_unit_formula' : {'$node', 'fof_and_formula', 1, ['$1', '$3'], nil, nil}.
'fof_unary_formula' -> 'tilde' 'fof_unit_formula' : {'$node', 'fof_unary_formula', 0, ['$2'], '$1', nil}.
'fof_unary_formula' -> 'fof_infix_unary' : '$1'.
'fof_infix_unary' -> 'fof_term' 'not_equal' 'fof_term' : {'$node', 'fof_infix_unary', 0, ['$1', '$3'], nil, nil}.
'fof_unit_formula' -> 'fof_unitary_formula' : '$1'.
'fof_unit_formula' -> 'fof_unary_formula' : '$1'.
'fof_unitary_formula' -> 'fof_quantified_formula' : '$1'.
'fof_unitary_formula' -> 'fof_atomic_formula' : '$1'.
'fof_unitary_formula' -> 'lparen' 'fof_logic_formula' 'rparen' : {'$node', 'fof_unitary_formula', 2, ['$2'], '$1', '$3'}.
'fof_quantified_formula' -> 'fof_quantifier' 'lbracket' 'fof_variable_list' 'rbracket' 'colon' 'fof_unit_formula' : {'$node', 'fof_quantified_formula', 0, ['$1', '$3', '$6'], nil, nil}.
'fof_variable_list' -> 'variable' : '$1'.
'fof_variable_list' -> 'variable' 'comma' 'fof_variable_list' : {'$node', 'fof_variable_list', 1, ['$1', '$3'], nil, nil}.
'fof_atomic_formula' -> 'fof_plain_atomic_formula' : '$1'.
'fof_atomic_formula' -> 'fof_defined_atomic_formula' : '$1'.
'fof_atomic_formula' -> 'fof_system_atomic_formula' : '$1'.
'fof_plain_atomic_formula' -> 'fof_plain_term' : '$1'.
'fof_defined_atomic_formula' -> 'fof_defined_plain_formula' : '$1'.
'fof_defined_atomic_formula' -> 'fof_defined_infix_formula' : '$1'.
'fof_defined_plain_formula' -> 'fof_defined_plain_term' : '$1'.
'fof_defined_infix_formula' -> 'fof_term' 'equal' 'fof_term' : {'$node', 'fof_defined_infix_formula', 0, ['$1', '$3'], nil, nil}.
'fof_system_atomic_formula' -> 'fof_system_term' : '$1'.
'fof_plain_term' -> 'constant' : '$1'.
'fof_plain_term' -> 'functor' 'lparen' 'fof_arguments' 'rparen' : {'$node', 'fof_plain_term', 1, ['$1', '$3'], nil, '$4'}.
'fof_defined_term' -> 'defined_term' : '$1'.
'fof_defined_term' -> 'fof_defined_atomic_term' : '$1'.
'fof_defined_atomic_term' -> 'fof_defined_plain_term' : '$1'.
'fof_defined_plain_term' -> 'defined_constant' : '$1'.
'fof_defined_plain_term' -> 'defined_functor' 'lparen' 'fof_arguments' 'rparen' : {'$node', 'fof_defined_plain_term', 1, ['$1', '$3'], nil, '$4'}.
'fof_system_term' -> 'system_constant' : '$1'.
'fof_system_term' -> 'system_functor' 'lparen' 'fof_arguments' 'rparen' : {'$node', 'fof_system_term', 1, ['$1', '$3'], nil, '$4'}.
'fof_arguments' -> 'fof_term' : '$1'.
'fof_arguments' -> 'fof_term' 'comma' 'fof_arguments' : {'$node', 'fof_arguments', 1, ['$1', '$3'], nil, nil}.
'fof_term' -> 'fof_function_term' : '$1'.
'fof_term' -> 'variable' : '$1'.
'fof_function_term' -> 'fof_plain_term' : '$1'.
'fof_function_term' -> 'fof_defined_term' : '$1'.
'fof_function_term' -> 'fof_system_term' : '$1'.
'fof_sequent' -> 'fof_formula_tuple' 'gentzen_arrow' 'fof_formula_tuple' : {'$node', 'fof_sequent', 0, ['$1', '$3'], nil, nil}.
'fof_sequent' -> 'lparen' 'fof_sequent' 'rparen' : {'$node', 'fof_sequent', 1, ['$2'], '$1', '$3'}.
'fof_formula_tuple' -> 'lbracket' 'rbracket' : {'$node', 'fof_formula_tuple', 0, [], '$1', '$2'}.
'fof_formula_tuple' -> 'lbracket' 'fof_formula_tuple_list' 'rbracket' : {'$node', 'fof_formula_tuple', 1, ['$2'], '$1', '$3'}.
'fof_formula_tuple_list' -> 'fof_logic_formula' 'comma_fof_logic_formula_rep' : {'$node', 'fof_formula_tuple_list', 0, ['$1'] ++ '$2', nil, nil}.
'comma_fof_logic_formula' -> 'comma' 'fof_logic_formula' : '$2'.
'cnf_formula' -> 'cnf_disjunction' : '$1'.
'cnf_formula' -> 'lparen' 'cnf_formula' 'rparen' : {'$node', 'cnf_formula', 1, ['$2'], '$1', '$3'}.
'cnf_disjunction' -> 'cnf_literal' : '$1'.
'cnf_disjunction' -> 'cnf_disjunction' 'vline' 'cnf_literal' : {'$node', 'cnf_disjunction', 1, ['$1', '$3'], nil, nil}.
'cnf_literal' -> 'fof_atomic_formula' : '$1'.
'cnf_literal' -> 'tilde' 'fof_atomic_formula' : {'$node', 'cnf_literal', 1, ['$2'], '$1', nil}.
'cnf_literal' -> 'tilde' 'lparen' 'fof_atomic_formula' 'rparen' : {'$node', 'cnf_literal', 2, ['$3'], '$1', '$4'}.
'cnf_literal' -> 'fof_infix_unary' : '$1'.
'thf_quantifier' -> 'tff_quantifier' : '$1'.
'thf_quantifier' -> 'th0_quantifier' : '$1'.
'thf_quantifier' -> 'type_quantifier' : '$1'.
'thf_unary_connective' -> 'tilde' : {'$leaf', 'tilde', 0, '$1'}.
'thf_unary_connective' -> 'ntf_short_connective' : '$1'.
'th0_quantifier' -> 'lambda' : {'$leaf', 'lambda', 0, '$1'}.
'th0_quantifier' -> 'choice' : {'$leaf', 'choice', 1, '$1'}.
'th0_quantifier' -> 'desc' : {'$leaf', 'desc', 2, '$1'}.
'type_quantifier' -> 'type_forall' : {'$leaf', 'type_forall', 0, '$1'}.
'type_quantifier' -> 'type_exists' : {'$leaf', 'type_exists', 1, '$1'}.
'tff_unary_connective' -> 'tilde' : {'$leaf', 'tilde', 0, '$1'}.
'tff_unary_connective' -> 'ntf_short_connective' : '$1'.
'tff_quantifier' -> 'fof_quantifier' : '$1'.
'tff_quantifier' -> 'hash' : {'$leaf', 'hash', 1, '$1'}.
'fof_quantifier' -> 'forall' : {'$leaf', 'forall', 0, '$1'}.
'fof_quantifier' -> 'exists' : {'$leaf', 'exists', 1, '$1'}.
'nonassoc_connective' -> 'iff' : {'$leaf', 'iff', 0, '$1'}.
'nonassoc_connective' -> 'implies' : {'$leaf', 'implies', 1, '$1'}.
'nonassoc_connective' -> 'impliedby' : {'$leaf', 'impliedby', 2, '$1'}.
'nonassoc_connective' -> 'xor' : {'$leaf', 'xor', 3, '$1'}.
'nonassoc_connective' -> 'nor' : {'$leaf', 'nor', 4, '$1'}.
'nonassoc_connective' -> 'nand' : {'$leaf', 'nand', 5, '$1'}.
'assoc_connective' -> 'vline' : {'$leaf', 'vline', 0, '$1'}.
'assoc_connective' -> 'ampersand' : {'$leaf', 'ampersand', 1, '$1'}.
'typeable_atom' -> 'constant' : '$1'.
'typeable_atom' -> 'distinct_object' : '$1'.
'atomic_type' -> 'typeable_atom' : '$1'.
'atomic_type' -> 'defined_constant' : '$1'.
'atomic_type' -> 'system_type' : '$1'.
'type_constant' -> 'type_functor' : {'$node', 'type_constant', 0, ['$1'], nil, nil}.
'type_functor' -> 'atomic_word' : {'$node', 'type_functor', 0, ['$1'], nil, nil}.
'defined_type' -> 'dollar_word' : {'$node', 'defined_type', 0, ['$1'], nil, nil}.
'system_type' -> 'dollar_dollar_word' : {'$node', 'system_type', 0, ['$1'], nil, nil}.
'constant' -> 'functor' : {'$node', 'constant', 0, ['$1'], nil, nil}.
'functor' -> 'atomic_word' : {'$node', 'functor', 0, ['$1'], nil, nil}.
'defined_constant' -> 'defined_functor' : {'$node', 'defined_constant', 0, ['$1'], nil, nil}.
'defined_functor' -> 'dollar_word' : {'$node', 'defined_functor', 0, ['$1'], nil, nil}.
'system_constant' -> 'system_functor' : {'$node', 'system_constant', 0, ['$1'], nil, nil}.
'system_functor' -> 'dollar_dollar_word' : {'$node', 'system_functor', 0, ['$1'], nil, nil}.
'th1_defined_term' -> 'big_forall' : {'$leaf', 'big_forall', 0, '$1'}.
'th1_defined_term' -> 'big_exists' : {'$leaf', 'big_exists', 1, '$1'}.
'th1_defined_term' -> 'big_choice' : {'$leaf', 'big_choice', 2, '$1'}.
'th1_defined_term' -> 'big_desc' : {'$leaf', 'big_desc', 3, '$1'}.
'th1_defined_term' -> 'big_equal' : {'$leaf', 'big_equal', 4, '$1'}.
'defined_term' -> 'number' : '$1'.
'defined_term' -> 'distinct_object' : '$1'.
'variable' -> 'upper_word' : {'$node', 'variable', 0, ['$1'], nil, nil}.
'source' -> 'dag_source' : '$1'.
'source' -> 'internal_source' : '$1'.
'source' -> 'external_source' : '$1'.
'source' -> 'lbracket' 'sources' 'rbracket' : {'$node', 'source', 3, ['$2'], '$1', '$3'}.
'sources' -> 'source' : '$1'.
'sources' -> 'source' 'comma' 'sources' : {'$node', 'sources', 1, ['$1', '$3'], nil, nil}.
'dag_source' -> 'name' : '$1'.
'dag_source' -> 'inference_record' : '$1'.
'inference_record' -> 'kw_inference' 'lparen' 'inference_rule' 'comma' 'useful_info' 'comma' 'parents' 'rparen' : {'$node', 'inference_record', 0, ['$3', '$5', '$7'], '$1', '$8'}.
'inference_rule' -> 'atomic_word' : {'$node', 'inference_rule', 0, ['$1'], nil, nil}.
'internal_source' -> 'kw_introduced' 'lparen' 'intro_type' 'comma' 'useful_info' 'comma' 'parents' 'rparen' : {'$node', 'internal_source', 0, ['$3', '$5', '$7'], '$1', '$8'}.
'intro_type' -> 'atomic_word' : {'$node', 'intro_type', 0, ['$1'], nil, nil}.
'external_source' -> 'file_source' : '$1'.
'file_source' -> 'kw_file' 'lparen' 'file_name' 'file_info' 'rparen' : {'$node', 'file_source', 0, ['$3', '$4'], '$1', '$5'}.
'file_info' -> 'comma' 'name' : {'$node', 'file_info', 0, ['$2'], '$1', nil}.
'file_info' -> '$empty' : nil.
'parents' -> 'lbracket' 'rbracket' : {'$node', 'parents', 0, [], '$1', '$2'}.
'parents' -> 'lbracket' 'parent_list' 'rbracket' : {'$node', 'parents', 1, ['$2'], '$1', '$3'}.
'parent_list' -> 'parent_info' 'comma_parent_info_rep' : {'$node', 'parent_list', 0, ['$1'] ++ '$2', nil, nil}.
'comma_parent_info' -> 'comma' 'parent_info' : '$2'.
'parent_info' -> 'source' 'parent_details' : {'$node', 'parent_info', 0, ['$1', '$2'], nil, nil}.
'parent_details' -> 'colon' 'general_term' : {'$node', 'parent_details', 0, ['$2'], '$1', nil}.
'parent_details' -> '$empty' : nil.
'optional_info' -> 'comma' 'useful_info' : {'$node', 'optional_info', 0, ['$2'], '$1', nil}.
'optional_info' -> '$empty' : nil.
'useful_info' -> 'general_list' : '$1'.
'include' -> 'kw_include' 'lparen' 'file_name' 'include_optionals' 'rparen' 'dot' : {'$node', 'include', 0, ['$3', '$4'], '$1', '$6'}.
'include_optionals' -> '$empty' : nil.
'include_optionals' -> 'comma' 'formula_selection' : {'$node', 'include_optionals', 1, ['$2'], '$1', nil}.
'include_optionals' -> 'comma' 'formula_selection' 'comma' 'space_name' : {'$node', 'include_optionals', 2, ['$2', '$4'], '$1', nil}.
'formula_selection' -> 'lbracket' 'name_list' 'rbracket' : {'$node', 'formula_selection', 0, ['$2'], '$1', '$3'}.
'formula_selection' -> 'star' : {'$leaf', 'star', 1, '$1'}.
'name_list' -> 'name' : '$1'.
'name_list' -> 'name' 'comma' 'name_list' : {'$node', 'name_list', 1, ['$1', '$3'], nil, nil}.
'space_name' -> 'name' : '$1'.
'general_term' -> 'general_data' : '$1'.
'general_term' -> 'general_data' 'colon' 'general_term' : {'$node', 'general_term', 1, ['$1', '$3'], nil, nil}.
'general_term' -> 'general_list' : '$1'.
'general_data' -> 'atomic_word' : '$1'.
'general_data' -> 'general_function' : '$1'.
'general_data' -> 'variable' : '$1'.
'general_data' -> 'number' : '$1'.
'general_data' -> 'distinct_object' : '$1'.
'general_data' -> 'formula_data' : '$1'.
'general_function' -> 'atomic_word' 'lparen' 'general_terms' 'rparen' : {'$node', 'general_function', 0, ['$1', '$3'], nil, '$4'}.
'formula_data' -> 'dw_thf' 'lparen' 'thf_formula' 'rparen' : {'$node', 'formula_data', 0, ['$1', '$3'], nil, '$4'}.
'formula_data' -> 'dw_tff' 'lparen' 'tff_formula' 'rparen' : {'$node', 'formula_data', 1, ['$1', '$3'], nil, '$4'}.
'formula_data' -> 'dw_fof' 'lparen' 'fof_formula' 'rparen' : {'$node', 'formula_data', 2, ['$1', '$3'], nil, '$4'}.
'formula_data' -> 'dw_cnf' 'lparen' 'cnf_formula' 'rparen' : {'$node', 'formula_data', 3, ['$1', '$3'], nil, '$4'}.
'formula_data' -> 'dw_fot' 'lparen' 'fof_term' 'rparen' : {'$node', 'formula_data', 4, ['$1', '$3'], nil, '$4'}.
'general_list' -> 'lbracket' 'rbracket' : {'$node', 'general_list', 0, [], '$1', '$2'}.
'general_list' -> 'lbracket' 'general_terms' 'rbracket' : {'$node', 'general_list', 1, ['$2'], '$1', '$3'}.
'general_terms' -> 'general_term' 'comma_general_term_rep' : {'$node', 'general_terms', 0, ['$1'] ++ '$2', nil, nil}.
'comma_general_term' -> 'comma' 'general_term' : '$2'.
'name' -> 'atomic_word' : {'$node', 'name', 0, ['$1'], nil, nil}.
'name' -> 'integer' : {'$node', 'name', 1, ['$1'], nil, nil}.
'atomic_word' -> 'lower_word' : '$1'.
'atomic_word' -> 'single_quoted' : '$1'.
'atomic_word' -> 'back_quoted' : '$1'.
'number' -> 'integer' : '$1'.
'number' -> 'rational' : '$1'.
'number' -> 'real' : '$1'.
'file_name' -> 'atomic_word' : {'$node', 'file_name', 0, ['$1'], nil, nil}.
'comma_thf_logic_formula_rep' -> '$empty' : [].
'comma_thf_logic_formula_rep' -> 'comma_thf_logic_formula' 'comma_thf_logic_formula_rep' : ['$1' | '$2'].
'comma_tff_term_rep' -> '$empty' : [].
'comma_tff_term_rep' -> 'comma_tff_term' 'comma_tff_term_rep' : ['$1' | '$2'].
'comma_fof_logic_formula_rep' -> '$empty' : [].
'comma_fof_logic_formula_rep' -> 'comma_fof_logic_formula' 'comma_fof_logic_formula_rep' : ['$1' | '$2'].
'comma_parent_info_rep' -> '$empty' : [].
'comma_parent_info_rep' -> 'comma_parent_info' 'comma_parent_info_rep' : ['$1' | '$2'].
'comma_general_term_rep' -> '$empty' : [].
'comma_general_term_rep' -> 'comma_general_term' 'comma_general_term_rep' : ['$1' | '$2'].
'atomic_word' -> 'kw_inference' : {'$leaf', 'lower_word', 0, '$1'}.
'atomic_word' -> 'kw_introduced' : {'$leaf', 'lower_word', 0, '$1'}.
'atomic_word' -> 'kw_file' : {'$leaf', 'lower_word', 0, '$1'}.
